services:
  varnish:
    image: varnish:7.5.0-alpine
    container_name: varnish
    restart: unless-stopped
    volumes:
      - "./default.vcl:/etc/varnish/default.vcl"
    ports:
      - "80:80"
    environment:
      - VARNISH_SIZE=2G
    networks:
      - render-demo
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - data:/usr/share/nginx/html
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8090:8080"
    networks:
      - render-demo
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - cluster.name=render-demo
      - node.name=render-demo
      - ES_JAVA_OPTS=-Xms2g -Xmx4g
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - render-demo
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - node.name=render-demo
      - cluster.name=render-demo
    networks:
      - render-demo
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  render-demo:
    external: true

volumes:
  esdata:
    driver: local
    driver_opts:
      type: none
      device: /home/sebas/IdeaProjects/render-demo/infra/es_data # Cambiar por la ruta correcta
      o: bind
  data:
    driver: local
    driver_opts:
      type: none
      device: /home/sebas/IdeaProjects/render-demo/static # Cambiar por la ruta correcta
      o: bind
